### ISSUE TITLE
Clickable menu buttons respond to right & middle mouse buttons

### ISSUE THREAD

**Issue by rpaladin** [BabylonJS/SpacePirates#5]
Clickable buttons such as these:
1)
![image](https://user-images.githubusercontent.com/69180012/167184826-f66e6c0c-e6d5-4979-b7c6-5bb6d97a64b0.png)
2)
![image](https://user-images.githubusercontent.com/69180012/167184894-430e1049-074f-4f38-b947-bc64cec4de7e.png)
3)
![image](https://user-images.githubusercontent.com/69180012/167184940-086a0ed7-09c6-4ae0-ac0f-bf2d91a92d6b.png)

Are responding to right & middle mouse buttons, when they should instead only be responsive to a left mouse button.

<hr />

Edit: Perhaps the right mouse button should be switched out in favor of a `Back page` function? Similar to a `Back button` function.

**Comment by CedricGuillemet** [comment]
ping @darraghjburke

**Comment by darraghjburke** [comment]
We could make these buttons respond only to LMB, but I don't know if it's necessary. Since RMB and MMB aren't bound to anything in the game menus, I think it's fine to allow you to click the menu buttons using any mouse button.

I went ahead and disabled the context menu, though. It does distract from the game if you right click and bring it up.

**Comment by rpaladin** [comment]
O.K, thanks for the clarification!
